WasafiRetPr/WasafiRet/urls.py
from django.urls import path
from . import views

urlpatterns = [
   
    path('category_list/',views.category_list,name='category_list'),
    path('category_create/',views.category_create,name='category_create'),
    path('category_update/<int:product_id>', views.category_update, name='category_update'),
    path('category_delete/<int:product_id>', views.category_delete, name='category_delete'),
    path('',views.product_list,name='product_list'),
    path('product_create/', views.product_create, name='product_create'),
    path('product_delete/<int:product_id>', views.product_delete, name='product_delete'),
    path('product_update/<int:product_id>', views.product_update, name='product_update'),
    path('search/', views.search, name='search'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/add/<int:product_id>',views.add_to_cart,name='add_to_cart'),
    path('cart/update/<int:cart_item_id>',views.update_cart,name='update_cart'),
    path('cart/remove/<int:cart_item_id>',views.remove_cart,name='remove_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('detail/<int:product_id>/', views.detail, name='detail'),
    

]

WasafiRetPr/WasafiRetPr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WasafiRet.urls')),
    path('orders/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('flashsale/',include('flashsale.urls')),
    path('auth/', include('accounts.urls', namespace='auth')),
    path('review/', include('review.urls')),
   
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

WasafiRetPr/accounts/urls.py
from django.urls import path

from .import views 
app_name='auth'
urlpatterns=[
    path('login/',views.user_login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.user_logout,name='logout'),
    path('profile',views.user_profile, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
    path('profile/security/', views.security_settings_view, name='security_settings'),
    

]

WasafiRetPr/order/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('history/', views.order_history, name='order_history'),
    path('cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
]

WasafiRetPr/WasafiRet/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100)

    def _str__(self):
        return self.name
    
class Product(models.Model):
    name=models.CharField(max_length=255)
    description=models.TextField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    is_active=models.BooleanField(default=True)
    image=models.ImageField(upload_to=',media/images',blank=True,null=True)

    def __str__(self):
        return self.name

class Cart(models.Model):
    user=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Cart {self.id} for {self.user.username}'
    
class CartItem(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} x {self.product.name} in Cart {self.cart.id}'
    
    def get_total(self):
        return self.quantity*self.product.price

WasafiRetPr/WasafiRet/forms.py
from django import forms
from .models import Product,Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=['name']
      
class ProductCreateForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=['name','description','price','stock','category','image','is_active']

WasafiRetPr/WasafiRet/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Product,Category,Cart,CartItem
from .forms import ProductCreateForm,CategoryForm
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.http import HttpResponseBadRequest
from django.db.models import Q
from flashsale.models import Flashsale
from django.utils import timezone
from review.models import Review

# Create your view here.


def category_list(request):
     categories=Category.objects.all()
     return render(request,'WasafiRet/category_list.html',{'categories':categories}) 

def category_create(request):
     if request.method == 'POST':
          form=CategoryForm(request.POST,request.FILES)
          if form.is_valid():
            form.save()
            return redirect('product_list')
     else:
          form=CategoryForm()
          
     return render(request,'WasafiRet/category_create.html',{'form':form})
def category_update(request,id):
     categories=get_object_or_404(Category,id=id)
     if request.method=='POST':
          form=CategoryForm(request.POST,request.FILES,instance=categories)
          if form.is_valid():
               form.save()
               return redirect('product_list')
          else:
               form=CategoryForm(instance=categories)
          return render(request,'WasafiRet/category_update.html',{'form':form,'categories':categories})
def category_delete(request,id):
     categories=get_object_or_404(Category,id=id)
     if request.method=='POST':
          categories.delete()
          return redirect('product_list')
     return render(request,'WasafiRet/category_delete.html',{'categories':categories})


def product_list(request):
    products=Product.objects.all()
    current = timezone.now()
    flashsale=Flashsale.objects.filter(start_time__lte=current,end_time__gte=current)
   
    paginator=Paginator(products,10,orphans=10,allow_empty_first_page=True)
    page=request.GET.get('page')
    try:
         paginated_products=paginator.page(page)
    except PageNotAnInteger:
         paginated_products=paginator.page(1)
    except EmptyPage:
         paginated_products=paginator.page(paginator.num_pages)

         
    return render(request, 'WasafiRet/product.html',{'products':paginated_products,'flashsale':flashsale})

def product_create(request):
     if request.method == 'POST':
          form=ProductCreateForm(request.POST,request.FILES)
          if form.is_valid():
            form.save()
            return redirect('product_list')
     else:
          form=ProductCreateForm()
     return render(request, 'WasafiRet/product_create.html',{'form':form})



def product_update(request,id):
     product=get_object_or_404(Product,id=id)
     if request.method=='POST':
          form=ProductCreateForm(request.POST,request.FILES,instance=product)
          if form.is_valid():
               form.save()
               return redirect('product_list')
          else:
               form=ProductCreateForm(instance=product)
          return render(request,'WasafiRet/product_update.html',{'form':form,'product':product})
def product_delete(request,id):
     product=get_object_or_404(Product,id=id)
     if request.method=='POST':
        product.delete()
        return redirect('product_list')
    
     return render(request,'WasafiRet/product_delete.html',{'product':product})


def search(request):
     search_query=request.POST.get('search_query','')
    
     products=Product.objects.filter(Q(name__icontains=search_query))
     context={
          'products':products,
          'search_query':search_query,
     }
     return render(request,'WasafiRet/search.html',context)
    
def view_cart(request):
    cart=Cart.objects.filter(user=request.user).first()
    cart_items=CartItem.objects.filter(cart=cart)

    cart_total=sum(item.get_total() for item in cart_items)
    return render(request, 'WasafiRet/cart.html', {'cart_items':cart_items, 'cart_total':cart_total})
def add_to_cart(request,product_id):
     product=Product.objects.get(id=product_id)
     cart,created=Cart.objects.get_or_create(user=request.user)
     cart_item,created=CartItem.objects.get_or_create(cart=cart,product=product)

     if not created:
          cart_item.quantity+=1
     else:
          cart_item.quantity=1

     cart_item.save()
     return redirect('view_cart')
def update_cart(request,cart_item_id):
     cart_item=get_object_or_404(CartItem,id=cart_item_id)
     
     if request.method =='POST':
          new=int(request.POST.get('quantity',0))
          if new>0:
               cart_item.quantity=new
               cart_item.save()
          else:
               return HttpResponseBadRequest("Invalid quantity")
          return redirect('view_cart')
     return HttpResponseBadRequest("Invalid request method")
def remove_cart(request,cart_item_id):
  
     cart_item=get_object_or_404(CartItem,id=cart_item_id)

     
     if request.method in ['POST','GET']:
        cart_item.delete()
     
        return redirect('view_cart')
     return HttpResponseBadRequest("Invalid request method")
    

def checkout(request):
    return render(request, 'WasafiRet/checkout.html')


def detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    reviews=product.reviews.all()
    
    return render(request, 'WasafiRet/product_detail.html', {'product': product,'reviews':reviews})

def main(request):
     current=timezone.now()
     flashsale=Flashsale.objects.filter(start_time__lte=current,end_time__gte=current)
     return render(request, 'WasafiRet/product.html',{'flashsale':flashsale})
     

WasafiRetPr/WasafiRet/templates/WasafiRet/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Wasafi Ret{% endblock %}</title>
  
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
      <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">Wasafi Ret</a>
        <div class="col-6 d-flex justify-content-center">
          <form
            class="mx-auto"
           
            method="POST"
            action="{% url 'search' %}"
          >
            {% csrf_token %}
            <div class="input-group">
              <input
                class="form-control w-50"
                type="text"
                name="search_query"
                placeholder="Search products"
              />
              <div class="input-group-append">
                <button class="fa fa-search" type="submit">Search</button>
              </div>
            </div>
          </form>
        </div>

        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'product_list' %}">Product</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'view_cart' %}"><i class="fas fa-shopping-cart"></i>Cart</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'category_create' %}">Category create</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="{% url 'product_create' %}">Product create</a>
            </li>
           <li class="nav-item user-greeting">
            <span class="navbar-text">
<i class= "fas fa-user"></i>
          {% if user.is_authenticated %} Hi {{ user.first_name }} {% else %} Hi
          User {% endif %}</span></li>
           <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          
                  Settings</a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
               <a class="dropdown-item" href="{% url 'auth:profile' %}">
                 Profile
                </a>
                <a class="dropdown-item" href="{% url 'auth:logout' %}">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            {% else %}
                <a class="dropdown-item" href="{% url 'auth:login' %}">
                    <i class="fas fa-sign-in-alt"></i> Login
                </a>
                <a class="dropdown-item" href="{% url 'auth:register' %}">
                    <i class="fas fa-user-plus"></i> Sign Up
                </a>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>

    <main class="container mt-5">{% block content %}{% endblock %}</main>

    <footer class="text-center mt-5">
      <p>&copy; 2024 Wasafi Ret. All rights reserved.</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

WasafiRetPr/WasafiRet/templates/WasafiRet/cart.html
{% extends 'WasafiRet/base.html' %}
{% load static %}
{% block title %}Shopping Cart - Wasafi Ret{% endblock %}
{% block content %}
<div class="container mt-5">
  <h1>Your Cart</h1>

  {% if cart_items %}
  <table class="table table-bordered table-striped mt-4">
    <thead class="thead-dark">
      <tr>
        <th>Image</th>
        <th>Product Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart_items %}
      <tr>
        <td>
          {% if item.product.image %}
          <img
            src="{{ item.product.image.url }}"
            class="img-fluid rounded"
            alt="{{ item.product.name }}"
            style="max-height: 100px"
          />
          {% else %}
          <img
            src="{% static 'images/default-product.jpg' %}"
            class="img-fluid rounded"
            alt="Default Product Image"
            style="max-height: 100px"
          />
          {% endif %}
          <form
            method="POST"
            action="{% url 'update_cart' item.id %}"
            style="display: inline"
          >
            {% csrf_token %}
            <input
              type="number"
              name="quantity"
              value="{{ item.quantity }}"
              min="1"
            />
            <button type="submit">Update</button>
          </form>
         
        </td>
        <td>{{ item.product.name }}</td>
        <td>${{ item.product.price }}</td>
        <td>{{ item.quantity }}</td>
        <td>${{ item.get_total }}</td>
        <td> <a
          href="{% url 'remove_cart' item.id %}"
          class="btn btn-danger btn-sm"
          >Remove</a
        ></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="row mb-5">
    <div class="col-md-6 text-left">
      <a href="{% url 'product_list' %}" class="btn btn-primary btn-lg">Continue Shopping</a>
    </div>
    <div class="col-md-6 text-right">
      <a href="{% url 'orders:checkout' %}" class="btn btn-success btn-lg">Proceed to Checkout</a>
    </div>
  </div>

  <div class="text-right">
    <h3>Total: ${{ cart_total }}</h3>
  </div>

  {% else %}
  <div class="alert alert-warning mt-5">
    <strong>Your cart is empty.</strong> Start adding some products!
  </div>
  {% endif %}
</div>
{% endblock %}

WasafiRetPr/WasafiRet/templates/WasafiRet/category_create.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title %}Category
create - Wasafi Ret{% endblock %} {% block content %}
<h1>Add New Category</h1>
<form method="POST">
  {% csrf_token %} {{ form.as_p }}

  <button type="submit">Save</button>
</form>
{% endblock %}

WasafiRetPr/WasafiRet/templates/WasafiRet/category_delete.html
{% extends 'WasafiRet/base.html' %} {% block content %}

<h1>Delete category</h1>

<div class="card-body">
  <form method="POST" action="{% url 'category_delete' product.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger me-2">Delete product</button>
    <a href="{% url 'product_list' %}" class="btn btn-primary">Cancel</a>
  </form>

  {% endblock content %}
</div>

WasafiRetPr/WasafiRet/templates/WasafiRet/category_list.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title %}Product
Detail - Wasafi Ret{% endblock %} {% block content %}
<h1>Category List</h1>
<a href="{% url 'category_create' %}">Add New Category</a>
<ul>
  {% for category in categories %}
  <li>{{ category.name }}</li>
  {% endfor %}
</ul>
{% endblock %}

WasafiRetPr/WasafiRet/templates/WasafiRet/category_update.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title %}Category
update - Wasafi Ret{% endblock %} {% block content %}
<h1>Update category</h1>

<form method="POST" action="{% url 'Category_update' product.id %}">
  {% csrf_token %}{{form.as_p}}

  <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock content %}

WasafiRetPr/WasafiRet/templates/WasafiRet/product.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title %}Product
List - Wasafi Ret{% endblock %} {% block content %}
<div class="container mt-5">
  <h1>Flash Sale Items</h1>
  <div class="slideshow">
    <div class="row mb-4">
      {% for item in flashsale %}
      <div class="myslides">
        <div class="col-md-4 mb-4">
          <a href="{% url 'flashsale' %}">
            <img
              src="{{ item.image.url }}"
              alt="{{ item.name }}"
              class="img-fluid flashsale-img"
            />
          </a>
        </div>
      </div>
      {% empty %}
      <p>No flash sale items available.</p>
      {% endfor %}
    </div>
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>

  <div style="text-align: center">
    {% for item in flashsale %}
    <span class="dot" onclick="currentSlide({{ forloop.counter }})"></span>
    {% endfor %}
  </div>

  <script src="{% static 'js/flash.js' %}"></script>

  <h1 class="mb-4">Product List</h1>
  <div class="row">
    {% for product in products %}
    <div class="col-md-3 mb-4">
      <div class="card h-100" style="max-height: 350px">
        {% if product.image %}
        <img
          src="{{ product.image.url }}"
          class="card-img-top"
          alt="Product Image"
        />
        {% else %}
        <img
          src="{% static 'images/default-product.jpg' %}"
          class="card-img-top"
          alt="Default Product Image"
        />
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">Price: {{ product.price }}</p>
          <p class="card-text">Stock: {{ product.stock }}</p>
        </div>
        <div class="card-footer">
          <a href="{% url 'detail' product.id %}" class="btn btn-primary"
            >View Details</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

WasafiRetPr/WasafiRet/templates/WasafiRet/product_create.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title %}Product
Detail - Wasafi Ret{% endblock %} {% block content %}
<h1>Product Create</h1>

<h1>Add New Product</h1>
<form method="POST">
  {% csrf_token %} {{ form.as_p }}
 
  <button type="submit">Save</button>
</form>
{% endblock %}

WasafiRetPr/WasafiRet/templates/WasafiRet/product_delete.html
{% extends 'WasafiRet/base.html' %} {% block content %}

<h1>Delete product</h1>

<div class="card-body">
  <form method="POST" action="{% url 'product_delete' product.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger me-2">Delete product</button>
    <a href="{% url 'product_list' %}" class="btn btn-primary">Cancel</a>
  </form>

  {% endblock content %}
</div>

WasafiRetPr/WasafiRet/templates/WasafiRet/product_detail.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title %}{{
product.name }} - Wasafi Ret{% endblock %} {% block content %}
<div class="container mt-5">
  <h1>{{ product.name }}</h1>
  <div class="row">
    <div class="col-md-6">
      {% if product.image %}
      <img
        src="{{ product.image.url }}"
        class="img-fluid"
        alt="{{ product.name }}"
        style="max-height: 400px"
      />
      {% else %}
      <img
        src="{% static 'images/default-product.jpg' %}"
        class="img-fluid"
        alt="Default Product Image"
        style="max-height: 400px"
      />
      {% endif %}
    </div>
    <div class="col-md-6">
      <h2>${{ product.price }}</h2>
      <p>{{ product.description }}</p>
      <ul>
        {% if product.feature_1 %}
        <li>{{ product.feature_1 }}</li>
        {% endif %} {% if product.feature_2 %}
        <li>{{ product.feature_2 }}</li>
        {% endif %} {% if product.feature_3 %}
        <li>{{ product.feature_3 }}</li>
        {% endif %}
      </ul>
      <div class="mt-3">
        <a href="{% url 'add_to_cart' product.id %}" class="btn btn-primary"
          >Add to Cart</a
        >
        <a href="{% url 'add_review' product.id %}" class="btn btn-secondary"
          >View Reviews</a
        >
      </div>
      <h2>Reviews</h2>
      {% if reviews %}
      <ul>
        {% for review in reviews %}
        <li>
          <strong>{{ review.user }}</strong> rated {{ review.rating }}<br />
          {{ review.comment }}<br />
          <small>Posted on: {{ review.created_at }}</small>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p>No reviews yet.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

WasafiRetPr/WasafiRet/templates/WasafiRet/product_update.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title
%}Product-Update - Wasafi Ret{% endblock %} {% block content %}
<h1>Update product</h1>

<form method="POST" action="{% url 'product_update' product.id %}">
  {% csrf_token %}{{form.as_p}}

  <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock content %}

WasafiRetPr/WasafiRet/templates/WasafiRet/search.html
{% extends 'WasafiRet/base.html' %} {% load static %} {% block title %}Product
List - Wasafi Ret{% endblock %} {% block content %}
    <title>Product Search Results</title>
</head>
<body>
    <h1>Search Results</h1>

  
    {% if search_query %}
        <p>Results for: <strong>{{ search_query }}</strong></p>
    {% endif %}

    
    {% if products.exists %}
    <div class="row">
        
           
          {% for product in products %}
    <div class="col-md-3 mb-4">
      <div class="card h-100" style="max-height: 350px">
        {% if product.image %}
        <img
          src="{{ product.image.url }}"
          class="card-img-top"
          alt="Product Image"
          style="width: 100%; height: 150px; object-fit: cover"
        />
        {% else %}
        <img
          src="{% static 'images/default-product.jpg' %}"
          class="card-img-top"
          alt="Default Product Image"
          style="width: 100%; height: 150px; object-fit: cover"
        />
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">Price: {{ product.price }}</p>
          <p class="card-text">Stock: {{ product.stock }}</p>
        </div>
        <div class="card-footer">
          <a href="{% url 'detail' product.id %}" class="btn btn-primary"
            >View Details</a
          >
        </div>
      </div>
      </div>
      {% endfor %}
      </div>
    {% else %}
     
        <p>No products found for "{{ search_query }}".</p>
        
    {% endif %}
{% endblock %}